version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_passwd
      POSTGRES_DB: demo_db
    ports:
      - 5432:5432
